### ISSUE TITLE
Weird output format when using bedtools

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/resources#840]
In [this Jupyter notebook](https://github.com/RobertsLab/project-gigas-oa-meth/blob/master/notebooks/2019-09-15-DML-Analysis.ipynb) I characterized the overlaps between *C. gigas* MI and various genome feature files. The code worked well except for when I tried to write the overlaps between MI and [introns](https://eagle.fish.washington.edu/trilobite/Crassostrea_gigas_v9_tracks/Cgigas_v9_intron.gff) or [putative promoters](https://eagle.fish.washington.edu/trilobite/Crassostrea_gigas_v9_tracks/Cgigas_v9_1k5p_gene_promoter.gff) to a tab-delimited file:

<img width="360" alt="Screen Shot 2020-02-13 at 9 20 36 AM" src="https://user-images.githubusercontent.com/22335838/74460675-1a0ba400-4e42-11ea-94fe-5343939cef11.png">

There seems to be some sort of gap between the columns/something that's splitting one row of data into multiple rows such that the columns don't align. It's easier to see in the actual files:

- [MI-Intron output](https://github.com/RobertsLab/project-gigas-oa-meth/blob/master/analyses/2019-09-15-DML-Analysis/2020-02-11-Intron-MI.txt)
- [MI-Promoter output](https://github.com/RobertsLab/project-gigas-oa-meth/blob/master/analyses/2019-09-15-DML-Analysis/2020-02-11-Promoter-MI.txt)

This was not an issue when I previously used `bedtools` to find overlaps between *C. gigas* DML and introns:

<img width="757" alt="Screen Shot 2020-02-13 at 9 23 05 AM" src="https://user-images.githubusercontent.com/22335838/74460860-740c6980-4e42-11ea-9f00-e01b87b35ea0.png">

## Is there a reason why this is happening to these 2 tracks and not the others? How can I reformat the files/ensure they are created properly?

**Comment by kubu4** [comment]
Your previous command that worked uses the `-wb` flag, but the command that's putting out the weird output is using the `-wo` flag. Is this part of the problem?

**Comment by yaaminiv** [comment]
Doesn't look like it:

![Screen Shot 2020-02-13 at 9 38 58 AM](https://user-images.githubusercontent.com/22335838/74462209-b5057d80-4e44-11ea-82ba-e35f32dc2f25.png)

**Comment by kubu4** [comment]
Sidenote, but why do you precede some your commands with a space after the `!`? Does it have any impact if you run the command w/o the extra space?

e.g. 

`!{bedtoolsDirectory}intersectBed `

vs.

`! {bedtoolsDirectory}intersectBed`

**Comment by yaaminiv** [comment]
> Sidenote, but why do you precede some your commands with a space after the !? Does it have any impact if you run the command w/o the extra space?

I had weird past experiences where `!{bedtoolsDirectory}intersectBed` would throw up an error and not run  but `! {bedtoolsDirectory}intersectBed` would! Don't know why, but I guess that's not really an issue anymore. It doesn't change the output:

<img width="303" alt="Screen Shot 2020-02-13 at 9 46 46 AM" src="https://user-images.githubusercontent.com/22335838/74462854-c13e0a80-4e45-11ea-961e-bc372a46968c.png">

**Comment by sr320** [comment]
So this is what you want to do...

```
Write the original A and B entries plus the number of base pairs of overlap between the two features. Only A features with overlap are reported. Restricted by -f and -r.
```

and instead what is it writing out?

**Comment by sr320** [comment]
IOW - talk about what you want to do in terms of "A" and "B" and what is actually happening

**Comment by yaaminiv** [comment]
> and instead what is it writing out?

It is still writing the original A and B + # of base pairs that overlap between the two. However, the actual output format (the columns) are not correctly tab-delimited. This is clearest when I tried importing the file into R to create a figure (R Markdown script [here]()):

![Screen Shot 2020-02-13 at 9 55 42 AM](https://user-images.githubusercontent.com/22335838/74463791-38c06980-4e47-11ea-9e93-c504a995ae35.png)

**Comment by sr320** [comment]
url for Cgigas_v9_intron.gff ?

thanks
Steven


Steven B. Roberts, Associate Professor
Associate Director - Graduate Program Coordinator
School of Aquatic and Fishery Sciences
University of Washington
Fisheries Teaching and Research (FTR) Building - Office 232
1140 NE Boat Street - Seattle, WA 98105
robertslab.info - sr320@uw.edu - @sr320
vm:206.866.5141 - cell:360.362.3626

**Comment by sr320** [comment]
never mind - found it

**Comment by sr320** [comment]
Try switching the order of A and B like you did for the one that worked (DML)

**Comment by yaaminiv** [comment]
> Try switching the order of A and B like you did for the one that worked (DML)

Still getting output that isn't correctly tab-delimited:

![Screen Shot 2020-02-13 at 10 50 17 AM](https://user-images.githubusercontent.com/22335838/74467814-a02de780-4e4e-11ea-841f-aa8cd470f30c.png)

![Screen Shot 2020-02-13 at 10 50 31 AM](https://user-images.githubusercontent.com/22335838/74467829-a8862280-4e4e-11ea-98d0-f0d0db0237c5.png)

**Comment by kubu4** [comment]
Is this part of the problem?

![image](https://user-images.githubusercontent.com/4514104/74467805-9ad09d00-4e4e-11ea-9d6c-c69fd783633f.png)

Also, can you please post link to that file (`2020-02-11-Methylation-Islands-500_0.02_50-filtered.tab.bed` so I can check it out?

**Comment by yaaminiv** [comment]
> Is this part of the problem?

Ah, forgot to rerun that code after I fixed the path! It is not part of the problem:

![Screen Shot 2020-02-13 at 10 51 41 AM](https://user-images.githubusercontent.com/22335838/74467919-d2d7e000-4e4e-11ea-9a2b-cfd55fb671a5.png)

> Also, can you please post link to that file (2020-02-11-Methylation-Islands-500_0.02_50-filtered.tab.bed so I can check it out?

[*C. gigas* methylation islands](https://github.com/RobertsLab/project-gigas-oa-meth/blob/master/analyses/2020-02-11-Characterizing-CpG-Methylation/2020-02-11-Methylation-Islands-500_0.02_50-filtered.tab.bed)

**Comment by kubu4** [comment]
I know this doesn't fix the problem, but you can see what's happening in the screenshot below:

![Screenshot from 2020-02-13 10-59-09](https://user-images.githubusercontent.com/4514104/74468868-6b229480-4e50-11ea-8e98-214b8a6a90e3.png)

Column 2 and Column three are getting characters inserted instead of tabs. Column 2 is getting `ct` added between the expected fields and Column 3 is getting `rn` OR `n`.

I think they might be coming from the `subtractBed` and `intrn` fields in the `Cgigas_v9_intron.gff`.

Why? I don't know, but maybe that'll help troubleshoot?

Also, you could try upgrading your version of bedtools and see if that helps.

**Comment by kubu4** [comment]
Also, this doesn't really help either, but the command works for me (with `-a` and `-b` files in either position):

![image](https://user-images.githubusercontent.com/4514104/74469936-6c54c100-4e52-11ea-9281-ff7c73f2453b.png)

I'm using bedtools 2.29.0

**Comment by kubu4** [comment]
I should clarify on my previous post. It "works" in the formatting aspect of things (i.e. output is properly tab-delimited).

HOWEVER, the results are _NOT_ the same!! The order of the input files seems to be critical. I don't have the time to look into what the implications are for putting files in `-a` vs. `-b` positions in the `intersectBed` command, but it appears to be important!

**Comment by yaaminiv** [comment]
> HOWEVER, the results are NOT the same!! The order of the input files seems to be critical. I don't have the time to look into what the implications are for putting files in -a vs. -b positions in the intersectBed command, but it appears to be important!

Yes I noticed that! I'm sticking to putting the genome feature track as `-a` and methylation islands as `-b` so I'm always getting bp counts of the genome feature track that overlaps with MI.

> I'm using bedtools 2.29.0

I'll update `bedtools` and try again

**Comment by yaaminiv** [comment]
Updating `bedtools` did the trick! Good reminder that I should always check to see if I'm using the latest version of the program.

![Screen Shot 2020-02-13 at 11 43 06 AM](https://user-images.githubusercontent.com/22335838/74471994-0833fc00-4e56-11ea-8511-dee6567f0008.png)
